name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main ]
  workflow_dispatch:

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1

      - name: setup Playwright
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          dotnet build
          playwright install

      - name: run tests
        env:
          TestConfig__BaseUrl: https://polite-glacier-04b4aa100.azurestaticapps.net/
        run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Results
          path: "**/*.trx"
          reporter: dotnet-trx